// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACrvhf4qjT5gj8uNNaBF6nB4G-TZARIgY',
    appId: '1:450772673983:web:f83d17572a88983bd1ed0a',
    messagingSenderId: '450772673983',
    projectId: 'smart-formation-projet',
    authDomain: 'smart-formation-projet.firebaseapp.com',
    storageBucket: 'smart-formation-projet.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzqNXxsvFen0j5YC678cYEH651IQB6_5Q',
    appId: '1:450772673983:android:a5e838619eb4c7a4d1ed0a',
    messagingSenderId: '450772673983',
    projectId: 'smart-formation-projet',
    storageBucket: 'smart-formation-projet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGNRMgmix8oPk-dLovh5C4t8S0Qluf8Mo',
    appId: '1:450772673983:ios:94fc44328984848dd1ed0a',
    messagingSenderId: '450772673983',
    projectId: 'smart-formation-projet',
    storageBucket: 'smart-formation-projet.appspot.com',
    iosBundleId: 'com.example.smartFormationProjet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGNRMgmix8oPk-dLovh5C4t8S0Qluf8Mo',
    appId: '1:450772673983:ios:19468da831f69829d1ed0a',
    messagingSenderId: '450772673983',
    projectId: 'smart-formation-projet',
    storageBucket: 'smart-formation-projet.appspot.com',
    iosBundleId: 'com.example.smartFormationProjet.RunnerTests',
  );
}
